### ISSUE TITLE
[TRACKING] Libs Release (`0.11.1`+`5.0.1+driver`)

### ISSUE THREAD

**Issue by Andreagit97** [falcosecurity/libs#1092]
This issue tracks the libs+driver release (`0.11.0`+`5.0.0+driver`). See the full release process here :point_down: 

https://github.com/falcosecurity/libs/blob/master/release.md
 
# Release Phases :cyclone: 

# Preparation :gift: 

- [x] Tag all necessary PR with milestones `0.11.0` and `5.0.0+driver`.

# Code freeze :cold_face: 

- [x] Test the libraries and drivers

# Release branch :arrow_down: 

- [x] Craft release branch 
         - upstream: https://github.com/falcosecurity/libs/tree/release/0.11.x
         - fork: https://github.com/Andreagit97/libs/tree/release/0.11.x
- [x] Release candidate tags for testing purposes. (optional)
    - https://github.com/falcosecurity/libs/releases/tag/0.11.0-rc1
    - https://github.com/falcosecurity/libs/releases/tag/0.11.0-rc2
    - https://github.com/falcosecurity/libs/releases/tag/0.11.0-rc3
    - https://github.com/falcosecurity/libs/releases/tag/0.11.0-rc4
    - https://github.com/falcosecurity/libs/releases/tag/0.11.0-rc5
    - https://github.com/falcosecurity/libs/releases/tag/5.0.0%2Bdriver
    - https://github.com/falcosecurity/libs/releases/tag/5.0.1%2Bdriver
    - https://github.com/falcosecurity/libs/releases/tag/0.11.0
    - https://github.com/falcosecurity/libs/releases/tag/0.11.1
    - https://github.com/falcosecurity/libs/releases/tag/0.11.2
- [x] open in [test-infra](https://github.com/falcosecurity/test-infra/blob/master/config/config.yaml) repository a PR to set the newly created branch as protected.
  - https://github.com/falcosecurity/test-infra/pull/1150

# Thaw :sunrise_over_mountains: 

- [x] thaw the repo allowing new PR to be merged in the `master` branch again.

# Final tags :label: 

- [x] craft them at the end of the release process
  - https://github.com/falcosecurity/libs/releases/tag/5.0.1%2Bdriver
  - https://github.com/falcosecurity/libs/releases/tag/0.11.0

# PR that should be cherry-picked into the release branch :cherries: 
- [x] https://github.com/falcosecurity/libs/pull/1095
- [x] https://github.com/falcosecurity/libs/pull/1098
- [x] https://github.com/falcosecurity/libs/pull/1100
- [x] https://github.com/falcosecurity/libs/pull/1102
- [x] https://github.com/falcosecurity/libs/pull/1103
- [x] https://github.com/falcosecurity/libs/pull/1105

Synced with: https://github.com/falcosecurity/libs/pull/1104

---

- [x] https://github.com/falcosecurity/libs/pull/1106
- [x] https://github.com/falcosecurity/libs/pull/1108

Synced with: https://github.com/falcosecurity/libs/pull/1107

---

- [x] https://github.com/falcosecurity/libs/pull/1112
- [x] https://github.com/falcosecurity/libs/pull/1113

Synced with: https://github.com/falcosecurity/libs/pull/1114

---

- [x] https://github.com/falcosecurity/libs/pull/1116
- [x] https://github.com/falcosecurity/libs/pull/1117

Synced with: https://github.com/falcosecurity/libs/pull/1118

---

- [x] https://github.com/falcosecurity/libs/pull/1120
- [x] https://github.com/falcosecurity/libs/pull/1121
- [x] https://github.com/falcosecurity/libs/pull/1122
- [x] https://github.com/falcosecurity/libs/pull/1123
- [x] https://github.com/falcosecurity/libs/pull/1124

Synced with: https://github.com/falcosecurity/libs/pull/1125

---

- [x] https://github.com/falcosecurity/libs/pull/1126
- [x] https://github.com/falcosecurity/libs/pull/1128

Synced with: https://github.com/falcosecurity/libs/pull/1129

---

- [x] https://github.com/falcosecurity/libs/pull/1130

Synced with: https://github.com/falcosecurity/libs/pull/1136

---

- [x] https://github.com/falcosecurity/libs/pull/1138

Synced with: https://github.com/falcosecurity/libs/pull/1140

---

- [x] https://github.com/falcosecurity/libs/pull/1143

Synced with: https://github.com/falcosecurity/libs/pull/1144

**Comment by Andreagit97** [comment]
Sync for the release branch https://github.com/falcosecurity/libs/pull/1104

**Comment by Andreagit97** [comment]
The new driver version for this release will be `5.0.1+driver`

**Comment by Andreagit97** [comment]
We entered the thawing phase! it took a bit but finally, we are ready to tag libraries!

**Comment by Andreagit97** [comment]
The latest libs tag is out: https://github.com/falcosecurity/libs/releases/tag/0.11.0

**Comment by Andreagit97** [comment]
In the next hours we will release a new libs tag `0.11.1` :rocket:

**Comment by Andreagit97** [comment]
The latest libs tag is out: https://github.com/falcosecurity/libs/releases/tag/0.11.1
