### ISSUE TITLE
[TRACKING] Libs Release (`0.13.0`)

### ISSUE THREAD

**Issue by Andreagit97** [falcosecurity/libs#1315]
This issue tracks the libs+driver release (`0.13.0`). See the full release process here :point_down: 

https://github.com/falcosecurity/libs/blob/master/release.md
 
# Release Phases :cyclone: 

# Preparation :gift: 

- [x] Tag all necessary PR with milestones `0.13.0`

# Code freeze :cold_face: 

- [x] Test the libraries and drivers

# Release branch :arrow_down: 

- [x] Craft release branch 
         - upstream: https://github.com/falcosecurity/libs/tree/release/0.13.x
         - fork: https://github.com/Andreagit97/libs/tree/release/0.13.x
- [x] Release candidate tags for testing purposes. (optional)
- [ ] start the drivers build on driver-kit
- [x] open in [test-infra](https://github.com/falcosecurity/test-infra/blob/master/config/config.yaml) repository a PR to set the newly created branch as protected.
   - https://github.com/falcosecurity/test-infra/pull/1228

# Thaw :sunrise_over_mountains: 

- [ ] thaw the repo allowing new PR to be merged in the `master` branch again.

# Final tags :label: 

- [ ] craft them at the end of the release process

# PR that should be cherry-picked into the release branch :cherries: 

- [x] https://github.com/falcosecurity/libs/pull/1321
- [x] https://github.com/falcosecurity/libs/pull/1322
- [x] https://github.com/falcosecurity/libs/pull/1323
- [x] https://github.com/falcosecurity/libs/pull/1324
- [x] https://github.com/falcosecurity/libs/pull/1329

Synced with: https://github.com/falcosecurity/libs/pull/1330

---

- [x] https://github.com/falcosecurity/libs/pull/839
- [x] https://github.com/falcosecurity/libs/pull/1332
- [x] https://github.com/falcosecurity/libs/pull/1331
- [x] https://github.com/falcosecurity/libs/pull/1334

Synced with: https://github.com/falcosecurity/libs/pull/1335

---

- [x] https://github.com/falcosecurity/libs/pull/1341
- [x] https://github.com/falcosecurity/libs/pull/1340

Synced with: https://github.com/falcosecurity/libs/pull/1344

---

- [x] https://github.com/falcosecurity/libs/pull/1349
- [x] https://github.com/falcosecurity/libs/pull/1350
- [x] https://github.com/falcosecurity/libs/pull/1345
- [x] https://github.com/falcosecurity/libs/pull/1339

Synced with: https://github.com/falcosecurity/libs/pull/1351

---

- [x] https://github.com/falcosecurity/libs/pull/1352

Synced with: https://github.com/falcosecurity/libs/pull/1353

---

- [x] https://github.com/falcosecurity/libs/pull/1354

Synced with: https://github.com/falcosecurity/libs/pull/1357

---

**Comment by Andreagit97** [comment]
We are in code freeze phase :cold_face:

**Comment by FedeDP** [comment]
Libs 0.13.0-rc1 and drivers 6.0.0+driver released!

**Comment by Andreagit97** [comment]
Due to https://github.com/falcosecurity/libs/pull/1341 we probably need to tag a 6.0.1+driver

**Comment by Andreagit97** [comment]
We released our final tags :tada: 
* https://github.com/falcosecurity/libs/releases/tag/0.13.0
* https://github.com/falcosecurity/libs/releases/tag/6.0.1%2Bdriver

We can declare the code thaw :) Thanks everyone for the precious help :pray:
