### ISSUE TITLE
[TRACKING] Patch release 0.13.1

### ISSUE THREAD

**Issue by Andreagit97** [falcosecurity/libs#1365]
Ideally, we would like to include these PR in the patch release:
- [x] https://github.com/falcosecurity/libs/pull/1363
- [x] https://github.com/falcosecurity/libs/pull/1362
- [x] https://github.com/falcosecurity/libs/pull/1360

The idea is to tag today or in the worst case tomorrow morning, let's see what we can do :/ 

# PR that should be cherry-picked into the release branch :cherries: 

- [x] https://github.com/falcosecurity/libs/pull/1363
- [x] https://github.com/falcosecurity/libs/pull/1362
- [x] https://github.com/falcosecurity/libs/pull/1360

Synced with: https://github.com/falcosecurity/libs/pull/1366

---
