### ISSUE TITLE
[TRACKING] Patch release 0.13.2

### ISSUE THREAD

**Issue by Andreagit97** [falcosecurity/libs#1399]
# Summary

We would like to include these PRs/issues in the patch release :point_right:  https://github.com/falcosecurity/libs/milestone/29

## PR that should be cherry-picked into the release branch :cherries: 

- [x] https://github.com/falcosecurity/libs/pull/1373
- [x] https://github.com/falcosecurity/libs/pull/1392
- [x] https://github.com/falcosecurity/libs/pull/1396
- [x] https://github.com/falcosecurity/libs/pull/1402
- [x] https://github.com/falcosecurity/libs/pull/1403
- [x] https://github.com/falcosecurity/libs/pull/1405 (reverted)
- [x] https://github.com/falcosecurity/libs/pull/1379

Synced with: https://github.com/falcosecurity/libs/pull/1412

---

Revert a commit with: https://github.com/falcosecurity/libs/pull/1413

---

/milestone 0.13.2

/assign @Andreagit97

**Comment by Andreagit97** [comment]
libs 0.13.2 has been released

**Comment by Andreagit97** [comment]
We removed a commit from sync https://github.com/falcosecurity/libs/pull/1413, this causes some issues with Falco and at the moment is not strictly necessary, so we will tag without it

**Comment by Andreagit97** [comment]
I will re-tag libs 0.13.2 as soon as we are sure we don't break anything

**Comment by Andreagit97** [comment]
libs 0.13.2-rc1 has been released

**Comment by Andreagit97** [comment]
Libs 0.13.2 has been released, thank you all!
