### ISSUE TITLE
[TRACKING] Libs Release (`0.14.0`)

### ISSUE THREAD

**Issue by Andreagit97** [falcosecurity/libs#1482]
This issue tracks the libs+driver release (`0.14.0`). See the full release process here :point_down: 

https://github.com/falcosecurity/libs/blob/master/release.md
 
See the milestone `0.14.0` for the target release day

# Release Phases :cyclone: 

# Preparation :gift: 

- [x] Tag all necessary PR with milestones `0.14.0`
- [x] Tag all necessary PR with milestones `next-driver`

# Code freeze :cold_face: 

- [x] Test the libraries and drivers

# Release branch :arrow_down: 

- [x] Craft release branch 
         - upstream: https://github.com/falcosecurity/libs/tree/release/0.14.x
         - fork: https://github.com/Andreagit97/libs/tree/release/0.14.x
- [x] Release candidate tags for testing purposes. Not needed
- [x] start the drivers build on driver-kit. Not needed
- [ ] open in [test-infra](https://github.com/falcosecurity/test-infra/blob/master/config/config.yaml) repository a PR to set the newly created branch as protected.
   - https://github.com/falcosecurity/test-infra/pull/1228

# Thaw :sunrise_over_mountains: 

- [x] thaw the repo allowing new PR to be merged in the `master` branch again.

# Final tags :label: 

- [x] craft them at the end of the release process

# PR that should be cherry-picked into the release branch :cherries: 

-

Synced with:

---

**Comment by Andreagit97** [comment]
The target PRs for this release are the ones labeled with milestones `0.14.0` and `next-driver`

**Comment by Andreagit97** [comment]
We would like to include the full cleanup of `k8s` and `mesos` enrichment engines (filter checks included) into this release

**Comment by Andreagit97** [comment]
Quick update on 0.14.0. We miss just 2 PR https://github.com/falcosecurity/libs/pulls?q=is%3Aopen+is%3Apr+milestone%3A0.14.0
* https://github.com/falcosecurity/libs/pull/1582 very easy, probably we will remove the entire job
* https://github.com/falcosecurity/libs/pull/1561 on my side should be ok, just pushed minor things, let's see if we all agree with the changes

After these 2 we can tag!

**Comment by Andreagit97** [comment]
Libs 0.14.0 is out https://github.com/falcosecurity/libs/releases/tag/0.14.0
