### ISSUE TITLE
[Tracking] Params inconsistencies in our drivers

### ISSUE THREAD

**Issue by Andreagit97** [falcosecurity/libs#515]
The aim of this issue is to track all the inconsistencies when we send event params from our drivers (BPF, kernel module) to userspace.

- [ ] Today when we send file descriptors `fd` to userspace, we send them as `int64_t` while they are represented on `int32_t`. This leads us to waste a lot of space in our ring buffers...  `fd` params are very common in our event, we waste `4` bytes every time we send a param of this type. Considering a small system, we can imagine that it could send also `1` million of `fd` params per second, this would mean wasting almost `4` MB of space in our ring buffers **per second**!
- [ ] Today when we send process identifiers `pid` to userspace, we send them as `int64_t` while they are represented on `int32_t`. This leads us to waste a lot of space in our ring buffers as explained in the previous `fd` case.
- [ ] In some syscalls we take the syscalls flags as an `int` value and we push it to userspace as `uint32_t` without converting it with our internal `PPM` representation.

**Comment by FedeDP** [comment]
Hi Andrea, like always, good catch! :D 

I agree with you; i'd phrase it in a different way actually:
"if we today are able to push to userspace 1mln fd-only events, we could instead push up to 2mln fd-only events"
This hits even harder :) 

To retain backward compatibility, i think we could:
* add a new `PT_FD32` and `PT_PID32`
* new drivers will send PT_PID32 and PT_FD32
* we are still compatible with old 64-bit types, while reading from scap files
* of course, bump maj schema version :/

**Comment by Andreagit97** [comment]
> Hi Andrea, like always, good catch! :D
> 
> I agree with you; i'd phrase it in a different way actually: "if we today are able to push to userspace 1mln fd-only events, we could instead push up to 2mln fd-only events" This hits even harder :)

:exploding_head: :exploding_head: 

> To retain backward compatibility, i think we could:
> 
>     * add a new `PT_FD32` and `PT_PID32`
> 
>     * new drivers will send PT_PID32 and PT_FD32
> 
>     * we are still compatible with old 64-bit types, while reading from scap files
> 
>     * of course, bump maj schema version :/
> 
> 
> This fixes the first 2 points; the last is a different case instead.

Completely agree with this solution!

**Comment by incertum** [comment]
Love it, big +1, great catch!

**Comment by FedeDP** [comment]
First 2 points will be addressed by #526

**Comment by Andreagit97** [comment]
I have slightly changed the issue format with `Generic event issues`  and `Specific event issues` in this way it should be more maintainable, thank you to @hbrueckner @Molter73 @FedeDP for all the help in finding new issues

**Comment by jasondellaluce** [comment]
Tracking down all of this is of incredible value. Thank you a lot!

**Comment by hbrueckner** [comment]
> I have slightly changed the issue format with `Generic event issues` and `Specific event issues` in this way it should be more maintainable, thank you to @hbrueckner @Molter73 @FedeDP for all the help in finding new issues

You are welcome! Many thanks @Andreagit97 for the excellent summary and tracker of all the review follow-ups!

**Comment by gnosek** [comment]
> "if we today are able to push to userspace 1mln fd-only events, we could instead push up to 2mln fd-only events"
This hits even harder :)

Optimism is awesome but let me cool it down a little bit :P Every event has this header, which is somewhat larger than the zero bytes it would need for that claim to be true ;)

```
struct ppm_evt_hdr {
#ifdef PPM_ENABLE_SENTINEL
    uint32_t sentinel_begin;
#endif
    uint64_t ts; /* timestamp, in nanoseconds from epoch */
    uint64_t tid; /* the tid of the thread that generated this event */
    uint32_t len; /* the event len, including the header */
    uint16_t type; /* the event type */
    uint32_t nparams; /* the number of parameters of the event */
};
```

BTW, we could probably easily change `nparams` to 16 bits. If we do expect >64k parameters, we can hack something for the (hopefully rare) events that exceed this number.

We could also trim the tid to 32 bits, but then we use this struct all over userspace too (#sadpanda), and other environments may want large tids (e.g. gvisor), so we would have to decouple these two structs and copy data field by field between them.

Don't let me distract you from tracking down the inconsistencies though, that's an awesome job!

These two changes would cut down 6 bytes from every event, equivalent to one and a half fds with no schema changes, just a major api version bump.

**Comment by FedeDP** [comment]
You are right, of course! Nonetheless, we are wasting lots of bytes that, all together, would:
* speed up pushing events (because we need to write, and later read, a little bit less on the ring buffer)
* clear up space for new events

I was a bit over-reacting though, agree ahah

> BTW, we could probably easily change nparams to 16 bits. If we do expect >64k parameters, we can hack something for the (hopefully rare) events that exceed this number.
We could also trim the tid to 32 bits, but then we use this struct all over userspace too (#sadpanda), and other environments may want large tids (e.g. gvisor), so we would have to decouple these two structs and copy data field by field between them.

Yep!

> Don't let me distract you from tracking down the inconsistencies though, that's an awesome job!

You gave thorough ideas! And data :D  

I think @Andreagit97 is working on porting current `modern-bpf` tests to work with kmod and old bpf; this should help us spot many more inconsistencies!

**Comment by incertum** [comment]
@oheifetz @therealbobo @FedeDP @Andreagit97 we all touched at least some inconsistencies and we just confirmed that for minor type confusions s32/u32 we will not create new events.

Could we get organized and address all these cases, but assign to folks beforehand so that we do not duplicate work?

Fixing all these would make the project look much better! I am happy to be reviewer, but also happy to help more if we don't find enough volunteers :)

**Comment by Andreagit97** [comment]
yeah agree with that we could write below this issue if someone is going to address some points of the list :)

**Comment by Andreagit97** [comment]
BTW I would avoid all changes that require a new event pair until we finally resolve the scap-file issue, unless we find something to fix ASAP

**Comment by Andreagit97** [comment]
I've added the `[NOT ADDRESSABLE]` marker to all issues that we cannot address now due to the scap-file management https://github.com/falcosecurity/libs/pull/1381#issuecomment-1746613905

**Comment by LucaGuerra** [comment]
Thank you Andrea, I think this makes it much clearer :pray:

**Comment by ecbadeaux** [comment]
@Andreagit97 Please mark dup3 as completed with strikethrough.

**Comment by ecbadeaux** [comment]
@incertum @Andreagit97 Can you guys also mark setns, flock, and unshare as complete?
