### ISSUE TITLE
[TRACKING] Libs Release

### ISSUE THREAD

**Issue by Andreagit97** [falcosecurity/libs#626]
As you may know for this libs release we will try a new form of release process using a release branch, you can find more details in this document :point_down: 

https://github.com/falcosecurity/libs/blob/33ca24e29790092cf5176fee5fd02cfaa1f5591a/release.md

We have already terminated the [preparation phase](https://github.com/falcosecurity/libs/blob/33ca24e29790092cf5176fee5fd02cfaa1f5591a/release.md#preparation) and all the PRs have the right milestone, so we can directly proceed with the [code freeze phase](https://github.com/falcosecurity/libs/blob/33ca24e29790092cf5176fee5fd02cfaa1f5591a/release.md#preparation)!

During this period the rationale is that no new-feature PRs are allowed to be merged (apart from [exceptions](https://github.com/falcosecurity/libs/blob/33ca24e29790092cf5176fee5fd02cfaa1f5591a/release.md#exceptions)). We will use this time to test the libraries before opening the release branch and tagging the code. Any help in testing is always welcome! :) 

As always we will use this issue to keep you updated about the release process, so if you need updates this is the right place to come :) 

# Release Phases

# Preparation

- [x] Tag all necessary PR with milestones `0.9.0` and `3.0.0+driver`.

# Code freeze

- [x] Test the libraries and drivers

# Release branch

- [x] Craft release branch 
         - upstream: https://github.com/falcosecurity/libs/tree/release/0.9.0
         - fork: https://github.com/Andreagit97/libs/tree/release/0.9.0
- [x] Release candidate tags should be created in the release branch for testing purposes.
        - [3.0.0+rc1-driver](https://github.com/falcosecurity/libs/releases/tag/3.0.0-rc1%2Bdriver)
        - [0.9.0+rc1](https://github.com/falcosecurity/libs/releases/tag/0.9.0-rc1)
- [x] opened in our [test-infra](https://github.com/falcosecurity/test-infra/blob/master/config/config.yaml) repository a PR to set the newly created branch as protected.
        - https://github.com/falcosecurity/test-infra/pull/866
# Thaw

- [x] thaw the repo allowing new PR to be merged in the `master` branch again.

# Final tags

- [ ] craft them at the end of the release process

# PR that should be cherry-picked into the release branch
- [x] https://github.com/falcosecurity/libs/pull/653
- [x] https://github.com/falcosecurity/libs/pull/652
- [x] https://github.com/falcosecurity/libs/pull/655
- [x] https://github.com/falcosecurity/libs/pull/656
- [x] https://github.com/falcosecurity/libs/pull/660
- [x] https://github.com/falcosecurity/libs/pull/661
- [x] https://github.com/falcosecurity/libs/pull/662
- [x] https://github.com/falcosecurity/libs/pull/663
- [x] https://github.com/falcosecurity/libs/pull/665
- [x] https://github.com/falcosecurity/libs/pull/669

# Sync PRs
- [x] https://github.com/falcosecurity/libs/pull/658
- [x] https://github.com/falcosecurity/libs/pull/664
- [x] https://github.com/falcosecurity/libs/pull/666
- [x] https://github.com/falcosecurity/libs/pull/670

**Comment by Andreagit97** [comment]
The code freeze starts today :cold_face:

**Comment by leogr** [comment]
whoa :cold_face:

**Comment by Andreagit97** [comment]
I think we have tested the drivers enough so I've opened the release branch :point_down: 
https://github.com/falcosecurity/libs/tree/release/0.9.0

I've also crafted 2 pre-release tag:
* [3.0.0+rc1-driver](https://github.com/falcosecurity/libs/releases/tag/3.0.0-rc1%2Bdriver)
* [0.9.0+rc1](https://github.com/falcosecurity/libs/releases/tag/0.9.0-rc1)

**Comment by Andreagit97** [comment]
This is the test-infra PR to protect the release branch :point_down: 
https://github.com/falcosecurity/test-infra/pull/866

**Comment by Andreagit97** [comment]
We have synched the release branch with the recent fixes :partying_face:  https://github.com/falcosecurity/libs/pull/658

**Comment by Andreagit97** [comment]
We have synched the release branch with the recent fixes partying_face https://github.com/falcosecurity/libs/pull/664

**Comment by Andreagit97** [comment]
We have synched the release branch with the recent fixes :robot: https://github.com/falcosecurity/libs/pull/666

**Comment by Andreagit97** [comment]
We have synched the release branch with the recent fixes :space_invader: https://github.com/falcosecurity/libs/pull/670

**Comment by Andreagit97** [comment]
We have released tag `0.9.0` for libs :partying_face: 
https://github.com/falcosecurity/libs/releases/tag/0.9.0

**Comment by jasondellaluce** [comment]
@Andreagit97, I think this can be closed now!

/close
