### ISSUE TITLE
 [TRACKING] Libs Release

### ISSUE THREAD

**Issue by FedeDP** [falcosecurity/libs#761]
As already shared during latest community call, we are nearing a libs (+ driver) release.

During this period the rationale is that no new-feature PRs are allowed to be merged (apart from [exceptions](https://github.com/falcosecurity/libs/blob/master/release.md#exceptions)). We will use this time to test the libraries before opening the release branch and tagging the code. Any help in testing is always welcome! :) 

This issue will be kept up to date with further changes.

See https://github.com/falcosecurity/libs/blob/master/release.md for an explanation of the release process.

# Release Phases

# Preparation

- [x] Tag all necessary PR with milestones `0.10.0` and `4.0.0+driver`

# Code freeze

- [x] Test the libraries and drivers

# Release branch

- [x] Craft release branch 
- [x] Release candidate tags should be created in the release branch for testing purposes.
- [x] open in our [test-infra](https://github.com/falcosecurity/test-infra/blob/master/config/config.yaml) repository a PR to set the newly created branch as protected -> https://github.com/falcosecurity/test-infra/pull/919

# Thaw

- [x] thaw the repo allowing new PR to be merged in the `master` branch again.

# Final tags

- [x] craft them at the end of the release process

**Comment by FedeDP** [comment]
Note: next driver version will be 4.0.0+driver, bumping major, because we bumped driver maj API version: https://github.com/falcosecurity/libs/pull/709

**Comment by FedeDP** [comment]
We reached code freeze; milestones `0.10.0` and `4.0.0+driver` are completed at the moment.
I will open a release branch soon.

**Comment by FedeDP** [comment]
Release branch is now up. The test-infra PR to set the new branch as protected has been opened: https://github.com/falcosecurity/test-infra/pull/919

I will tag RCs soon, and port them to Falco.

**Comment by FedeDP** [comment]
RC1 tags created: https://github.com/falcosecurity/libs/tags

**Comment by FedeDP** [comment]
Falco PR to bump to RCs is alive: https://github.com/falcosecurity/falco/pull/2302

**Comment by FedeDP** [comment]
A sync PR has been opened: https://github.com/falcosecurity/libs/pull/796.
This will lead us to 0.10.0 final tag.

**Comment by FedeDP** [comment]
Final tags are up :smile: 
* 4.0.0+driver -> https://github.com/falcosecurity/libs/releases/tag/4.0.0%2Bdriver
* 0.10.0 -> https://github.com/falcosecurity/libs/releases/tag/0.10.0

I declare master branch thaw :rocket:

**Comment by FedeDP** [comment]
We can close the tracking issue now :)

/close

**Comment by FedeDP** [comment]
/reopen

We will need a 0.10.1 release :)

**Comment by FedeDP** [comment]
The new release branch `release/0.10.x` is up; it is being set as protected in https://github.com/falcosecurity/test-infra/pull/945.

PR to sync new release branch is https://github.com/falcosecurity/libs/pull/827.
We should not need a new driver tag.

**Comment by FedeDP** [comment]
Old `release/0.10.0` branch has been resetted to the 0.10.0 tag.

**Comment by FedeDP** [comment]
New tag available: https://github.com/falcosecurity/libs/releases/tag/0.10.1
/close
