### ISSUE TITLE
Umbrella: Adding support for new field types in plugins

### ISSUE THREAD

**Issue by therealbobo** [falcosecurity/libs#990]
**Motivation**

Currently, the plugin API only supports `uint64` and `charbuf` field types. However, could be a good idea to add support for additional types to align with the `libsinsp` library.

**Feature**

The following types need to be added:
- [ ] `none`
- [ ] `int8`
- [ ] `int16`
- [ ] `int32`
- [ ] `int64`
- [ ] `uint8`
- [ ] `uint16`
- [ ] `uint32`
- [x] `uint64`
- [x] `bytebuf`
- [ ] `errno`
- [ ] `sockaddr`
- [ ] `socktuple`
- [ ] `fd`
- [ ] `pid`
- [ ] `fdlist`
- [ ] `fspath`
- [ ] `syscallid`
- [ ] `sigtype`
- [x] `reltime`
- [x] `abstime`
- [ ] `port`
- [ ] `l4proto`
- [ ] `sockfamily`
- [x] `bool`
- [ ] `ipv4addr`
- [ ] `dyn`
- [ ] `flags8`
- [ ] `flags16`
- [ ] `flags32`
- [ ] `uid`
- [ ] `gid`
- [ ] `double`
- [ ] `sigset`
- [ ] `charbufarray`
- [ ] `pt_charbuf_pair_array`
- [ ] `ipv4addr`
- [ ] `ipv4net`
- [ ] `ipv6addr`
- [ ] `ipv6net`
- [x] `ipaddr`
- [x] `ipnet`
- [ ] `mode`
- [ ] `fsrelpath`
- [ ] `enumflags8`
- [ ] `enumflags16`
- [ ] `enumflags32`
- [ ] `max`

Probably not all these types are useful.
Additionally adding all these types, maybe, could result in performance penalties.

**Tasks**

- [ ] Add support for new filtercheck types.
- [ ] Test the new filtercheck types.
- [ ] Ensure compatibility with `driver/ppm_events_public.h`.
- [ ] Update documentation to reflect the changes.

**Additional context**

These types should be compatible with the types declared in the `driver/ppm_events_public.h` in the [libs](https://github.com/falcosecurity/libs) repository.

_This issue will be used only for tracking._

**Comment by LucaGuerra** [comment]
Hey @therealbobo , I don't think we need all of them :) Also because perhaps the types that sinsp supports are a bit too many :)

I think it makes sense to start from a minimal list and add more when necessary

**Comment by therealbobo** [comment]
You are right! I already started to work on it! 😄

**Comment by leogr** [comment]
/milestone 0.13.0 assuming this is a long-term task
